### ISSUE TITLE
Support for jumping and crouching

### ISSUE THREAD

**Issue by vincent-io** [FakeYou/first-person#1]
Hi, I didn't see a `CONTRIBUTOR.md`, so I'm just firing away. Would be awesome if I could jump or crouch. To make it actually useful, the map should allow for "partial" walls of course.

**Comment by andrenanninga** [comment]
While jump and crouching would be awesome, it wouldn't fit in the current setup of the engine. Currently the entire game is really just a top-down 2d game but with a 3d renderer. The physics and levels are only every accounting for two dimensions. Add verticality in the game would add another dimension and it would mean that we would have to use another physics engine (one that can work in three dimensions) and create a new workflow for authoring maps.

For reference, this game is built almost exactly the same way as described in this video: [Making of Xibalba](https://www.youtube.com/watch?v=GEP7zJ9cQfw).
